{
 "title": "RHDG - Cache Statistics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cache_name",
    "label": "Cache Name",
    "query": "metrics(vendor_cache_manager_default_cache_.*_statistics_number_of_entries_in_memory)"
   },
   { "name": "instance", "label": "Instance", "query": "label_values(pod)" }
  ]
 },
 "panels": [
  {
   "title": "Objects",
   "type": "singlestat",
   "description": "Total number of distinct object",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries\"})*min({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_required_minimum_number_of_nodes\"})/min(vendor_cache_manager_default_cache_container_health_number_of_nodes)"
    }
   ]
  },
  {
   "title": "In Memory",
   "type": "singlestat",
   "description": "Total number including replicas",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\"})"
    }
   ]
  },
  {
   "title": "Evicted",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries\"})-sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\"})"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Objects on $instance for $cache_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries\",pod=~\"$instance\"})",
     "legendFormat": "Objects"
    },
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\",pod=~\"$instance\"})",
     "legendFormat": "Objects in memory"
    },
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries\",pod=~\"$instance\"})-sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\",pod=~\"$instance\"})",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Objects on $instance for $cache_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries\",pod=~\"$instance\"})",
     "legendFormat": "Objects"
    },
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\",pod=~\"$instance\"})",
     "legendFormat": "Objects in memory"
    },
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries\",pod=~\"$instance\"})-sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\",pod=~\"$instance\"})",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Objects on $instance for $cache_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries\",pod=~\"$instance\"})",
     "legendFormat": "Objects"
    },
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\",pod=~\"$instance\"})",
     "legendFormat": "Objects in memory"
    },
    {
     "expr": "sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries\",pod=~\"$instance\"})-sum({__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_number_of_entries_in_memory\",pod=~\"$instance\"})",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "Read/Write",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read/Write on $instance for $cache_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 14 },
     "repeat": "instance",
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_hits\",pod=~\"$instance\"}+{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_misses\",pod=~\"$instance\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_stores\",pod=~\"$instance\"}",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Read/Write on $instance for $cache_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_hits\",pod=~\"$instance\"}+{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_misses\",pod=~\"$instance\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_stores\",pod=~\"$instance\"}",
       "legendFormat": "Write"
      }
     ]
    },
    {
     "title": "Read/Write on $instance for $cache_name",
     "type": "graph",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_hits\",pod=~\"$instance\"}+{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_misses\",pod=~\"$instance\"}",
       "legendFormat": "Read"
      },
      {
       "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_stores\",pod=~\"$instance\"}",
       "legendFormat": "Write"
      }
     ]
    }
   ]
  },
  { "title": "Hits/Misses", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Query on $instance for $cache_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_hits\",pod=~\"$instance\"}",
     "legendFormat": "Hits"
    },
    {
     "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_misses\",pod=~\"$instance\"}",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Query on $instance for $cache_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_hits\",pod=~\"$instance\"}",
     "legendFormat": "Hits"
    },
    {
     "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_misses\",pod=~\"$instance\"}",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Query on $instance for $cache_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_hits\",pod=~\"$instance\"}",
     "legendFormat": "Hits"
    },
    {
     "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_misses\",pod=~\"$instance\"}",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Remove on $instance for $cache_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 23 },
   "repeat": "instance",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_remove_hits\",pod=~\"$instance\"}",
     "legendFormat": "Remove Hits"
    },
    {
     "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_remove_misses\",pod=~\"$instance\"}",
     "legendFormat": "Remove Misses"
    }
   ]
  },
  {
   "title": "Remove on $instance for $cache_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_remove_hits\",pod=~\"$instance\"}",
     "legendFormat": "Remove Hits"
    },
    {
     "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_remove_misses\",pod=~\"$instance\"}",
     "legendFormat": "Remove Misses"
    }
   ]
  },
  {
   "title": "Remove on $instance for $cache_name",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_remove_hits\",pod=~\"$instance\"}",
     "legendFormat": "Remove Hits"
    },
    {
     "expr": "{__name__=~\"vendor_cache_manager_default_cache_($cache_name)_statistics_remove_misses\",pod=~\"$instance\"}",
     "legendFormat": "Remove Misses"
    }
   ]
  }
 ]
}